/*
 * TEALsim - MIT TEAL Project
 * Copyright (c) 2004 The Massachusetts Institute of Technology. All rights reserved.
 * Please see license.txt in top level directory for full license.
 * 
 * http://icampus.mit.edu/teal/TEALsim
 * 
 * $Id: GeneratesP.java,v 1.5 2007/07/17 15:46:54 pbailey Exp $ 
 * 
 */

package teal.physics.em;

import javax.vecmath.Vector3d;

/**
 * Objects that generate a P field should implement <code>
 * GeneratesP</code>.  When a <code>World</code> responds to
 * <code>getP</code> requests, it will only sum up the P
 * fields of <code>GeneratesP</code> objects.
 */
public interface GeneratesP {

  /**
   * <code>getP</code> returns the P field at a position
   * and time.
   *
   * @param position a <code>Vector3D</code> representing where
   * to calculate the P field at.
   * @param time a <code>double</code> representing the <code>
   * World</code> time to calculate the magnetic field at.
   * @return a <code>Vector3d</code> representing the field
   * generated by this object.
   */
  Vector3d getP(Vector3d position, double time);

  /**
   * <code>getP</code> returns the Magnetic field at a position
   * at the current <code>World</code> time.
   *
   * @param position a <code>Vector3D</code> representing where
   * to calculate the electric field.
   * @return a <code>Vector3d</code> representing the field
   */
   Vector3d getP(Vector3d position);
   /**
   * <code>isGeneratingP</code> returns whether or not you are
   * currently generating a field.
   *
   * @return <code>true</code> if currently generating a
   * field, <code>false</code> otherwise
   */
  boolean isGeneratingP();
}
